### ISSUE TITLE
cluster-init.sh move?

### ISSUE THREAD

**Issue by timbuktuu** [tleyden/elastic-thought#3] opened 2015-02-16 22:31 UTC
Did cluster-init.sh move or is it replaced by generate-all.sh?

$ ./elasticthought-cluster-init.sh -v 3.0.1 -n 3 -u "user:passw0rd" -p gpu 
Kick off couchbase cluster
--2015-02-16 22:05:12--  https://raw.githubusercontent.com/couchbaselabs/couchbase-server-docker/master/scripts/cluster-init.sh
Resolving raw.githubusercontent.com... 199.27.76.133
Connecting to raw.githubusercontent.com|199.27.76.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-02-16 22:05:12 ERROR 404: Not Found.

**Comment by tleyden** [comment] 2015-02-16 22:58
Closing as dupe of #2

**Closed by tleyden** 2015-02-16 22:58 UTC
